/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Struct;
import java.util.ArrayList;

/**
 *
 * @author Ruben
 */
public class Principal extends javax.swing.JFrame 
{
    public ArrayList<DatosRouter> Routers;
    public ArrayList<Boolean> bR; //Saber que Routers estan en ejecucion
    public DatosRouter.nodo nodo;
    

    public Principal() 
    {
        this.Routers = new ArrayList<>();
        this.bR = new ArrayList<>();
        estructuraInicial();
        initComponents();
    }
    
    //Revisen que los datos iniciales esten bien
    public void estructuraInicial()
    {
        DatosRouter R1 = new DatosRouter(1);
        DatosRouter R2 = new DatosRouter(2);
        DatosRouter R3 = new DatosRouter(3);
        DatosRouter R4 = new DatosRouter(4);
        DatosRouter R5 = new DatosRouter(5);
        
         //192.168.0.x/30
        R1.setVecino(3, "192.168.0.1/30");
        R1.setNodo("10.0.1.0/24", "255.255.255.0", "10.0.1.1/24", 1, 1);
        
        R2.setVecino(3, "192.168.0.17/30");
        R2.setNodo("10.0.3.0/24", "255.255.255.0", "10.0.3.1/24", 1, 2);
        
        R3.setVecino(1, "192.168.0.2/30");
        R3.setVecino(2, "192.168.0.18/30");
        R3.setVecino(4, "192.168.0.5/30");
        R3.setVecino(5, "192.168.0.13/30");
        
        R4.setVecino(3, "192.168.0.6/30");
        R4.setVecino(5, "192.168.0.9/30");
        R4.setNodo("10.0.2.0/24", "255.255.255.0", "10.0.2.1/24", 1, 4);
        
        R5.setVecino(3, "192.168.0.14/30");
        R5.setVecino(4, "192.168.0.10/30");
        R5.setNodo("10.0.4.0/24", "255.255.255.0", "10.0.4.1/24", 1, 5);
        
        Routers.add(R1);
        Routers.add(R2);
        Routers.add(R3);
        Routers.add(R4);
        Routers.add(R5);
        
        bR.add(false);
        bR.add(false);
        bR.add(false);
        bR.add(false);
        bR.add(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRouter = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Principal");

        jLabel2.setText("Router");

        txtRouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRouterKeyTyped(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        if (!(txtRouter.getText() == ""))
        {
            //Crea un hilo y lo pone a ejecutar
            int r = Integer.parseInt(txtRouter.getText()) - 1;
            if (bR.get(r) == false)
            {
                Router rou = new Router(Routers.get(r));
                Thread hRou = new Thread(rou);
                hRou.start();
                rou.pasoInfoVecinos();
                bR.set(r, true);
            }
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtRouterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRouterKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!( (txtRouter.getText().length() < 1) &&
                (ch >= '0' && ch <= '5')))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRouterKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRouter;
    // End of variables declaration//GEN-END:variables
}
